spring.application.name=VehicleRental
spring.datasource.url=jdbc:mysql://localhost:3306/vehicle_rental?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@bhi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
